# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27eeca48c771db6c1504ed84fd4135b1cced49df6a02f42ca9acfbc16bde2238a74c5031a59d9006121f4a2605a36e093ebc303a044c8681a80e29aa0e17bf34

test:
  secret_key_base: 36ee607f832bb4a8e1606250301b710bf93d6f768545b908434fe9e82d35700198ed4959c83cd787bc57e5e97df42fa4ed3c6439147e1b8818df78ffa6fadb5c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
